apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-pipeline
secrets:
  - name: er-pull-secret
  - name: cicd-{{NAMESPACE}}
# er-pull-secret used to pull images from ER in Dockerfiles

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-mq-sa
secrets:
  - name: er-pull-secret
  - name: cicd-{{NAMESPACE}}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-ace-sa
secrets:
  - name: er-pull-secret
  - name: cicd-{{NAMESPACE}}
